### PR TITLE
Use macos as run target for all automations, Double workflow timeouts

### PR DESCRIPTION
**Pull request by BierDav**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Some things in yarn.lock looks like merge conflicts

**Comment by BierDav** [comment]
jup, wait i'm on it

**Comment by BierDav** [comment]
This should be it, i hope ;)

**Comment by BierDav** [comment]
image
I have stumpled upon this. This might be a bit a deal breaker, but I don't think that there is really another solution if we want to run unit tests also for native targets

**Comment by BierDav** [comment]
Ahh ok, nevermind for public repositories there is no limit and everything is free anyways.

**Comment by ligi** [comment]
yeah - tbh if it costs I would remove macOS stuff (not using any of these on my own) 
maybe we can mitigate by building linux and win stuff on linux worker (as far as I see this might be possible)
and only mcOS stuff on mc workers

**Comment by BierDav** [comment]
i don't think that this is worth the effort, because we only have two targets which can be compiled and tested on linux

**Comment by ligi** [comment]
I might still do that at some point - just do not trust these closed source machines ..-)

**Pull request merged**
